package com.fridgelist.app.ui.common

import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.drawWithContent
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Rect
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.ColorFilter
import androidx.compose.ui.graphics.Paint
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.vectorResource
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.fridgelist.app.data.model.IconCatalog
import com.fridgelist.app.data.model.IconCategory

/**
 * Renders a grocery icon by name.
 *
 * When a real SVG drawable asset (ic_grocery_<name>) is present it is used.
 * Until then, an emoji inside a category-coloured rounded square is shown so
 * the app is fully usable without any custom artwork.
 */
@Composable
fun GroceryIcon(
    iconName: String,
    contentDescription: String?,
    modifier: Modifier = Modifier,
    colorFilter: ColorFilter? = null
) {
    val context = LocalContext.current
    val resId = remember(iconName) {
        context.resources.getIdentifier(
            "ic_grocery_$iconName",
            "drawable",
            context.packageName
        )
    }

    if (resId != 0) {
        val vector = ImageVector.vectorResource(id = resId)
        Image(
            imageVector = vector,
            contentDescription = contentDescription,
            modifier = modifier,
            colorFilter = colorFilter
        )
    } else {
        val (emoji, _) = remember(iconName) { emojiAndColor(iconName) }

        BoxWithConstraints(
            modifier = modifier
                .then(
                    if (colorFilter != null)
                        Modifier.drawWithContent {
                            val paint = Paint().apply { this.colorFilter = colorFilter }
                            drawContext.canvas.saveLayer(
                                bounds = Rect(offset = Offset.Zero, size = size),
                                paint = paint
                            )
                            drawContent()
                            drawContext.canvas.restore()
                        }
                    else
                        Modifier
                ),
            contentAlignment = Alignment.Center
        ) {
            val fontSize = (minOf(maxWidth, maxHeight) * 0.75f).value.sp
            Text(
                text = emoji,
                fontSize = fontSize,
                textAlign = TextAlign.Center
            )
        }
    }
}

// ---------------------------------------------------------------------------
// Emoji + background colour resolution
// ---------------------------------------------------------------------------

private fun emojiAndColor(iconName: String): Pair<String, Color> {
    val category = IconCatalog.all.find { it.name == iconName }?.category
    val emoji = emojiMap[iconName]
        ?: category?.let { categoryFallbackEmoji[it] }
        ?: "🛒"
    val color = category?.let { categoryColors[it] } ?: Color(0xFFE0E0E0)
    return emoji to color
}

private val categoryColors = mapOf(
    IconCategory.VEGETABLES    to Color(0xFFCCE8CC),
    IconCategory.FRUIT         to Color(0xFFFFD6BC),
    IconCategory.DAIRY_EGGS    to Color(0xFFFFF9C4),
    IconCategory.MEAT          to Color(0xFFFFCDD2),
    IconCategory.FISH_SEAFOOD  to Color(0xFFBBDEFB),
    IconCategory.BAKERY        to Color(0xFFFFE0B2),
    IconCategory.DRY_GOODS     to Color(0xFFD7CCC8),
    IconCategory.OILS_CONDIMENTS to Color(0xFFF0F4C3),
    IconCategory.SPICES_HERBS  to Color(0xFFFFF8E1),
    IconCategory.DRINKS        to Color(0xFFE0F7FA),
    IconCategory.FROZEN        to Color(0xFFE3F2FD),
    IconCategory.SNACKS        to Color(0xFFFFE0B2),
    IconCategory.HOUSEHOLD     to Color(0xFFECEFF1),
    IconCategory.PERSONAL_CARE to Color(0xFFFCE4EC),
    IconCategory.BABY_PET      to Color(0xFFE8EAF6),
)

private val categoryFallbackEmoji = mapOf(
    IconCategory.VEGETABLES    to "🥬",
    IconCategory.FRUIT         to "🍎",
    IconCategory.DAIRY_EGGS    to "🥛",
    IconCategory.MEAT          to "🍖",
    IconCategory.FISH_SEAFOOD  to "🐟",
    IconCategory.BAKERY        to "🍞",
    IconCategory.DRY_GOODS     to "🌾",
    IconCategory.OILS_CONDIMENTS to "🫙",
    IconCategory.SPICES_HERBS  to "🌿",
    IconCategory.DRINKS        to "🥤",
    IconCategory.FROZEN        to "❄️",
    IconCategory.SNACKS        to "🍿",
    IconCategory.HOUSEHOLD     to "🏠",
    IconCategory.PERSONAL_CARE to "🧴",
    IconCategory.BABY_PET      to "🐾",
)

private val emojiMap = mapOf(
    // VEGETABLES
    "tomato"            to "🍅",
    "carrot"            to "🥕",
    "onion"             to "🧅",
    "garlic"            to "🧄",
    "potato"            to "🥔",
    "sweet_potato"      to "🍠",
    "broccoli"          to "🥦",
    "cauliflower"       to "🥦",
    "cabbage"           to "🥬",
    "lettuce"           to "🥬",
    "spinach"           to "🥬",
    "cucumber"          to "🥒",
    "bell_pepper"       to "🫑",
    "zucchini"          to "🥒",
    "eggplant"          to "🍆",
    "corn"              to "🌽",
    "peas"              to "🫛",
    "green_beans"       to "🫘",
    "mushroom"          to "🍄",
    "celery"            to "🌿",
    "leek"              to "🧅",
    "asparagus"         to "🌿",
    "pumpkin"           to "🎃",
    "beetroot"          to "🫀",
    "radish"            to "🌶️",
    "avocado"           to "🥑",
    "chili_pepper"      to "🌶️",
    "ginger"            to "🫚",
    "artichoke"         to "🌿",
    "kale"              to "🥬",
    "spring_onion"      to "🧅",
    "brussels_sprouts"  to "🥦",
    "bok_choy"          to "🥬",
    "fennel"            to "🌿",
    "parsnip"           to "🥕",
    "butternut_squash"  to "🎃",
    "swiss_chard"       to "🥬",
    "edamame"           to "🫘",
    "snow_peas"         to "🫛",
    "watercress"        to "🌿",
    "turnip"            to "🥔",
    "okra"              to "🌿",
    "shallot"           to "🧅",
    "celeriac"          to "🥔",
    "kohlrabi"          to "🥦",
    "radicchio"         to "🥬",
    "endive"            to "🥬",
    "baby_spinach"      to "🥬",
    "red_cabbage"       to "🥬",
    "savoy_cabbage"     to "🥬",
    "broccolini"        to "🥦",
    "romanesco"         to "🥦",
    "daikon"            to "🥕",
    "bitter_melon"      to "🥒",
    "water_chestnut"    to "🌰",
    "bamboo_shoots"     to "🌿",
    "lotus_root"        to "🌸",
    "arugula"           to "🥬",
    "microgreens"       to "🌱",
    "taro"              to "🍠",
    "yam"               to "🍠",
    "spaghetti_squash"  to "🎃",
    "purple_onion"      to "🧅",

    // FRUIT
    "apple"         to "🍎",
    "banana"        to "🍌",
    "orange"        to "🍊",
    "strawberry"    to "🍓",
    "grapes"        to "🍇",
    "watermelon"    to "🍉",
    "pineapple"     to "🍍",
    "mango"         to "🥭",
    "peach"         to "🍑",
    "pear"          to "🍐",
    "cherry"        to "🍒",
    "blueberry"     to "🫐",
    "raspberry"     to "🍓",
    "kiwi"          to "🥝",
    "melon"         to "🍈",
    "plum"          to "🍑",
    "lemon"         to "🍋",
    "lime"          to "🍋",
    "grapefruit"    to "🍊",
    "coconut"       to "🥥",
    "papaya"        to "🥭",
    "fig"           to "🫐",
    "pomegranate"   to "🍎",
    "passion_fruit" to "🍑",
    "apricot"       to "🍑",
    "clementine"    to "🍊",
    "cranberries"   to "🍒",
    "dates"         to "🌴",
    "dragon_fruit"  to "🍈",
    "blackberries"  to "🫐",
    "lychee"        to "🍒",
    "guava"         to "🍈",
    "persimmon"     to "🍊",
    "nectarine"     to "🍑",
    "tangerine"     to "🍊",
    "quince"        to "🍐",
    "starfruit"     to "⭐",
    "plantain"      to "🍌",
    "jackfruit"     to "🍈",
    "kumquat"       to "🍊",
    "gooseberry"    to "🍇",
    "mulberry"      to "🫐",
    "tamarind"      to "🌿",

    // DAIRY & EGGS
    "milk"            to "🥛",
    "butter"          to "🧈",
    "cheese"          to "🧀",
    "yogurt"          to "🥛",
    "eggs"            to "🥚",
    "heavy_cream"     to "🥛",
    "cream_cheese"    to "🧀",
    "sour_cream"      to "🥛",
    "mozzarella"      to "🧀",
    "parmesan"        to "🧀",
    "feta"            to "🧀",
    "ricotta"         to "🧀",
    "kefir"           to "🥛",
    "condensed_milk"  to "🥛",
    "whipping_cream"  to "🥛",
    "gouda"           to "🧀",
    "brie"            to "🧀",
    "cheddar"         to "🧀",
    "goat_cheese"     to "🧀",
    "cottage_cheese"  to "🧀",
    "buttermilk"      to "🥛",
    "halloumi"        to "🧀",
    "mascarpone"      to "🧀",
    "quark"           to "🥛",

    // MEAT
    "chicken_breast" to "🍗",
    "whole_chicken"  to "🐔",
    "ground_beef"    to "🥩",
    "steak"          to "🥩",
    "pork_chop"      to "🍖",
    "bacon"          to "🥓",
    "ham"            to "🍖",
    "sausage"        to "🌭",
    "turkey"         to "🦃",
    "lamb"           to "🐑",
    "chicken_thighs" to "🍗",
    "chicken_wings"  to "🍗",
    "chorizo"        to "🌭",
    "salami"         to "🍖",
    "pepperoni"      to "🍕",
    "duck"           to "🦆",
    "veal"           to "🥩",
    "hot_dogs"       to "🌭",
    "prosciutto"     to "🍖",
    "pastrami"       to "🥩",
    "ground_pork"    to "🥩",
    "pork_ribs"      to "🍖",
    "ground_turkey"  to "🦃",
    "mortadella"     to "🍖",
    "pancetta"       to "🥓",

    // FISH & SEAFOOD
    "salmon"        to "🐟",
    "canned_tuna"   to "🐟",
    "shrimp"        to "🦐",
    "fish_fillet"   to "🐟",
    "sardines"      to "🐟",
    "cod"           to "🐟",
    "mussels"       to "🦪",
    "crab"          to "🦀",
    "mackerel"      to "🐟",
    "smoked_salmon" to "🐟",
    "oysters"       to "🦪",
    "squid"         to "🦑",
    "trout"         to "🐟",
    "anchovies"     to "🐟",
    "sea_bass"      to "🐟",
    "scallops"      to "🦪",
    "octopus"       to "🐙",
    "herring"       to "🐟",
    "lobster"       to "🦞",
    "clams"         to "🦪",
    "sea_bream"     to "🐟",

    // BAKERY
    "bread"          to "🍞",
    "baguette"       to "🥖",
    "rolls"          to "🍞",
    "croissant"      to "🥐",
    "tortilla"       to "🫓",
    "pita"           to "🫓",
    "bagel"          to "🥯",
    "crackers"       to "🍘",
    "naan"           to "🫓",
    "sourdough"      to "🍞",
    "rye_bread"      to "🍞",
    "english_muffin" to "🫓",
    "muffin"         to "🧁",
    "brioche"        to "🍞",
    "focaccia"       to "🫓",
    "ciabatta"       to "🍞",
    "soft_pretzel"   to "🥨",
    "donut"          to "🍩",
    "waffles"        to "🧇",
    "flatbread"      to "🫓",
    "chapati"        to "🫓",
    "cornbread"      to "🌽",

    // DRY GOODS & PANTRY
    "rice"               to "🍚",
    "pasta"              to "🍝",
    "flour"              to "🌾",
    "sugar"              to "🍬",
    "salt"               to "🧂",
    "oats"               to "🌾",
    "breakfast_cereal"   to "🥣",
    "lentils"            to "🫘",
    "chickpeas"          to "🫘",
    "black_beans"        to "🫘",
    "canned_tomatoes"    to "🍅",
    "canned_corn"        to "🌽",
    "breadcrumbs"        to "🍞",
    "baking_powder"      to "🥄",
    "dark_chocolate"     to "🍫",
    "cocoa_powder"       to "🍫",
    "quinoa"             to "🌾",
    "couscous"           to "🍚",
    "coconut_milk"       to "🥥",
    "noodles"            to "🍜",
    "tomato_paste"       to "🍅",
    "vegetable_stock"    to "🥣",
    "yeast"              to "🍞",
    "chia_seeds"         to "🌱",
    "sunflower_seeds"    to "🌻",
    "brown_rice"         to "🍚",
    "whole_wheat_flour"  to "🌾",
    "cornmeal"           to "🌽",
    "red_kidney_beans"   to "🫘",
    "white_beans"        to "🫘",
    "granola"            to "🥣",
    "raisins"            to "🍇",
    "rice_noodles"       to "🍜",
    "soba_noodles"       to "🍜",
    "pumpkin_seeds"      to "🌱",
    "baking_soda"        to "🥄",
    "cornstarch"         to "🥄",
    "gelatin"            to "🍮",
    "miso_paste"         to "🫙",
    "protein_powder"     to "💪",
    "barley"             to "🌾",
    "buckwheat"          to "🌾",
    "polenta"            to "🌽",
    "semolina"           to "🌾",
    "dried_apricots"     to "🍑",
    "prunes"             to "🫐",
    "coconut_flakes"     to "🥥",
    "sesame_seeds"       to "🌱",

    // OILS, SAUCES & CONDIMENTS
    "olive_oil"             to "🫒",
    "vegetable_oil"         to "🫙",
    "vinegar"               to "🫙",
    "soy_sauce"             to "🫙",
    "tomato_sauce"          to "🍅",
    "ketchup"               to "🍅",
    "mayonnaise"            to "🥣",
    "mustard"               to "🌭",
    "hot_sauce"             to "🌶️",
    "pesto"                 to "🌿",
    "hummus"                to "🫘",
    "honey"                 to "🍯",
    "jam"                   to "🍓",
    "peanut_butter"         to "🥜",
    "chocolate_spread"      to "🍫",
    "tahini"                to "🫙",
    "coconut_oil"           to "🥥",
    "fish_sauce"            to "🐟",
    "bbq_sauce"             to "🍖",
    "teriyaki_sauce"        to "🍱",
    "maple_syrup"           to "🍁",
    "worcestershire_sauce"  to "🫙",
    "sesame_oil"            to "🫚",
    "balsamic_vinegar"      to "🫙",
    "apple_cider_vinegar"   to "🍎",
    "oyster_sauce"          to "🦪",
    "hoisin_sauce"          to "🫙",
    "sriracha"              to "🌶️",
    "ranch_dressing"        to "🥣",
    "caesar_dressing"       to "🥣",
    "agave_syrup"           to "🌵",
    "rice_vinegar"          to "🫙",
    "mirin"                 to "🫙",
    "harissa"               to "🌶️",
    "curry_paste"           to "🌶️",
    "gochujang"             to "🌶️",
    "salsa"                 to "🍅",

    // SPICES & HERBS
    "black_pepper"   to "🫙",
    "cumin"          to "🌾",
    "paprika"        to "🌶️",
    "oregano"        to "🌿",
    "basil"          to "🌿",
    "cinnamon"       to "🫙",
    "turmeric"       to "🌿",
    "chili_flakes"   to "🌶️",
    "bay_leaves"     to "🍃",
    "thyme"          to "🌿",
    "rosemary"       to "🌿",
    "vanilla"        to "🫙",
    "cardamom"       to "🌿",
    "nutmeg"         to "🌰",
    "curry_powder"   to "🌶️",
    "coriander"      to "🌿",
    "garlic_powder"  to "🧄",
    "mixed_herbs"    to "🌿",
    "saffron"        to "🌸",
    "star_anise"     to "⭐",
    "cloves"         to "🌿",
    "smoked_paprika" to "🌶️",
    "onion_powder"   to "🧅",
    "garam_masala"   to "🌶️",
    "fennel_seeds"   to "🌿",
    "dried_mint"     to "🌿",
    "dried_dill"     to "🌿",
    "dried_sage"     to "🌿",
    "zaatar"         to "🌿",
    "sumac"          to "🌶️",
    "allspice"       to "🌿",
    "mustard_seeds"  to "🌿",

    // DRINKS
    "water"          to "💧",
    "sparkling_water" to "💧",
    "orange_juice"   to "🍊",
    "coffee"         to "☕",
    "tea"            to "🍵",
    "beer"           to "🍺",
    "wine"           to "🍷",
    "cola"           to "🥤",
    "energy_drink"   to "⚡",
    "coconut_water"  to "🥥",
    "oat_milk"       to "🥛",
    "almond_milk"    to "🥛",
    "apple_juice"    to "🍎",
    "lemonade"       to "🍋",
    "kombucha"       to "🍵",
    "hot_chocolate"  to "☕",
    "green_tea"      to "🍵",
    "herbal_tea"     to "🍵",
    "tomato_juice"   to "🍅",
    "sports_drink"   to "🥤",
    "prosecco"       to "🥂",
    "soy_milk"       to "🥛",
    "rice_milk"      to "🥛",
    "matcha"         to "🍵",
    "chai"           to "☕",
    "ginger_beer"    to "🍺",
    "tonic_water"    to "💧",
    "bone_broth"     to "🍲",

    // FROZEN
    "frozen_pizza"      to "🍕",
    "ice_cream"         to "🍦",
    "frozen_vegetables" to "🥦",
    "frozen_fish"       to "🐟",
    "frozen_fries"      to "🍟",
    "frozen_berries"    to "🫐",
    "frozen_chicken"    to "🍗",
    "frozen_dumplings"  to "🥟",
    "frozen_waffles"    to "🧇",
    "ice"               to "🧊",
    "frozen_peas"       to "🫛",
    "frozen_shrimp"     to "🦐",
    "frozen_edamame"    to "🫘",
    "frozen_meatballs"  to "🍖",
    "popsicles"         to "🍭",
    "frozen_corn"       to "🌽",
    "frozen_spinach"    to "🥬",
    "frozen_soup"       to "🍲",
    "frozen_pot_pie"    to "🥧",

    // SNACKS
    "crisps"             to "🥔",
    "popcorn"            to "🍿",
    "mixed_nuts"         to "🥜",
    "chocolate_bar"      to "🍫",
    "cookies"            to "🍪",
    "candy"              to "🍬",
    "granola_bar"        to "🌾",
    "pretzels"           to "🥨",
    "rice_cakes"         to "🍘",
    "protein_bar"        to "💪",
    "beef_jerky"         to "🥩",
    "peanuts"            to "🥜",
    "cashews"            to "🥜",
    "almonds"            to "🥜",
    "dried_mango"        to "🥭",
    "trail_mix"          to "🥜",
    "walnuts"            to "🥜",
    "pistachios"         to "🥜",
    "dark_chocolate_bar" to "🍫",
    "white_chocolate_bar" to "🍫",
    "fruit_leather"      to "🍎",
    "sesame_snaps"       to "🌱",
    "pork_rinds"         to "🐷",
    "veggie_chips"       to "🥦",
    "seaweed_snacks"     to "🌿",
    "cheese_puffs"       to "🧀",
    "macadamia_nuts"     to "🥜",
    "dried_cranberries"  to "🍒",
    "coconut_chips"      to "🥥",

    // HOUSEHOLD
    "toilet_paper"        to "🧻",
    "paper_towels"        to "🧻",
    "dish_soap"           to "🫧",
    "laundry_detergent"   to "🧺",
    "trash_bags"          to "🗑️",
    "sponge"              to "🧽",
    "aluminum_foil"       to "🫙",
    "cling_film"          to "🫙",
    "zip_lock_bags"       to "🫙",
    "cleaning_spray"      to "🫧",
    "dishwasher_tablets"  to "🫧",
    "fabric_softener"     to "🌸",
    "candles"             to "🕯️",
    "batteries"           to "🔋",
    "light_bulb"          to "💡",
    "bleach"              to "🫧",
    "glass_cleaner"       to "🫧",
    "air_freshener"       to "🌸",
    "rubber_gloves"       to "🧤",
    "matches"             to "🔥",
    "laundry_pods"        to "🧺",
    "stain_remover"       to "🫧",
    "shoe_polish"         to "👟",
    "clothespins"         to "🪡",
    "toilet_brush"        to "🪣",
    "floor_cleaner"       to "🧹",
    "oven_cleaner"        to "🫧",
    "napkins"             to "🧻",
    "paper_plates"        to "🍽️",
    "coffee_filters"      to "☕",
    "mop"                 to "🧹",
    "broom"               to "🧹",
    "drain_cleaner"       to "🫧",
    "toilet_cleaner"      to "🪣",
    "insect_spray"        to "🐛",
    "parchment_paper"     to "📄",
    "tape"                to "📎",
    "lint_roller"         to "🎲",
    "laundry_mesh_bag"    to "🧺",
    "steel_wool"          to "🪣",

    // PERSONAL CARE
    "shampoo"                   to "🧴",
    "conditioner"               to "🧴",
    "body_wash"                 to "🧴",
    "toothpaste"                to "🦷",
    "toothbrush"                to "🪥",
    "deodorant"                 to "🧴",
    "razor"                     to "🪒",
    "tissues"                   to "🧻",
    "cotton_pads"               to "🌸",
    "sunscreen"                 to "☀️",
    "hand_cream"                to "🧴",
    "lip_balm"                  to "💄",
    "toilet_soap"               to "🧼",
    "face_wash"                 to "🧴",
    "moisturizer"               to "🧴",
    "mouthwash"                 to "🫧",
    "dental_floss"              to "🦷",
    "nail_polish_remover"       to "💅",
    "band_aids"                 to "🩹",
    "vitamins"                  to "💊",
    "wet_wipes"                 to "🧻",
    "perfume"                   to "🌸",
    "eye_drops"                 to "👁️",
    "pain_relief"               to "💊",
    "contact_lens_solution"     to "👁️",
    "feminine_hygiene_products" to "🌸",
    "hair_dye"                  to "💇",
    "q_tips"                    to "🌸",
    "hair_mask"                 to "💇",
    "face_mask"                 to "🧖",
    "toner"                     to "🧴",
    "nail_clippers"             to "💅",
    "foot_cream"                to "🧴",
    "dry_shampoo"               to "💇",

    // BABY & PET
    "baby_formula"          to "🍼",
    "diapers"               to "👶",
    "baby_food"             to "🥣",
    "baby_wipes"            to "🧻",
    "baby_lotion"           to "🧴",
    "baby_bottle"           to "🍼",
    "baby_shampoo"          to "🧴",
    "diaper_cream"          to "🧴",
    "pacifier"              to "👶",
    "baby_powder"           to "👶",
    "baby_cereal"           to "🥣",
    "baby_snacks"           to "🍪",
    "cat_food"              to "🐱",
    "dog_food"              to "🐕",
    "cat_treats"            to "🐱",
    "dog_treats"            to "🐕",
    "cat_litter"            to "🪣",
    "dog_poop_bags"         to "🐕",
    "fish_food"             to "🐠",
    "pet_shampoo"           to "🐾",
    "bird_food"             to "🐦",
    "hamster_food"          to "🐹",
    "rabbit_food"           to "🐰",
    "guinea_pig_food"       to "🐾",
    "turtle_food"           to "🐢",
    "ferret_food"           to "🐾",
    "cat_milk"              to "🐱",
    "dog_toy"               to "🎾",
    "cat_toy"               to "🧶",
    "dog_collar"            to "🐕",
    "dog_leash"             to "🐕",
    "flea_treatment"        to "🐾",
    "pet_vitamins"          to "💊",
    "cat_bowl"              to "🐱",
    "dog_bowl"              to "🐕",
)
